### ISSUE TITLE
1.20.4r1  error

### ISSUE THREAD

**Issue by unknowghost0** [jrbudda/Vivecraft_Spigot_Extensions#106]
i downloaded 1.20.4 and it just keep saying this 
[07:56:37 ERROR]: [DirectoryProviderSource] Error loading plugin: Directory 'plugins/Vivecraft_Spigot_Extensions.jar' failed to load!
java.lang.RuntimeException: Directory 'plugins/Vivecraft_Spigot_Extensions.jar' failed to load!
at io.papermc.paper.plugin.provider.source.FileProviderSource.registerProviders(FileProviderSource.java:59) ~[paper-1.20.4.jar:git-Paper-397]
at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.lambda$registerProviders$1(DirectoryProviderSource.java:34) ~[paper-1.20.4.jar:git-Paper-397]
at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845) ~[?:?]
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.registerProviders(DirectoryProviderSource.java:32) ~[paper-1.20.4.jar:git-Paper-397]
at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.registerProviders(DirectoryProviderSource.java:14) ~[paper-1.20.4.jar:git-Paper-397]
at io.papermc.paper.plugin.util.EntrypointUtil.registerProvidersFromSource(EntrypointUtil.java:14) ~[paper-1.20.4.jar:git-Paper-397]
at io.papermc.paper.plugin.PluginInitializerManager.load(PluginInitializerManager.java:100) ~[paper-1.20.4.jar:git-Paper-397]
at net.minecraft.server.Main.main(Main.java:131) ~[paper-1.20.4.jar:git-Paper-397]
at org.bukkit.craftbukkit.Main.main(Main.java:325) ~[paper-1.20.4.jar:git-Paper-397]
at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42) ~[app:?]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: org.bukkit.plugin.InvalidPluginException: java.util.zip.ZipException: zip file is empty
at io.papermc.paper.plugin.provider.source.FileProviderSource.checkUpdate(FileProviderSource.java:95) ~[paper-1.20.4.jar:git-Paper-397]
at io.papermc.paper.plugin.provider.source.FileProviderSource.registerProviders(FileProviderSource.java:49) ~[paper-1.20.4.jar:git-Paper-397]
... 20 more
Caused by: java.util.zip.ZipException: zip file is empty
at java.util.zip.ZipFile$Source.zerror(ZipFile.java:1762) ~[?:?]
at java.util.zip.ZipFile$Source.findEND(ZipFile.java:1546) ~[?:?]
at java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1641) ~[?:?]
at java.util.zip.ZipFile$Source.<init>(ZipFile.java:1479) ~[?:?]
at java.util.zip.ZipFile$Source.get(ZipFile.java:1441) ~[?:?]
at java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:718) ~[?:?]
at java.util.zip.ZipFile.<init>(ZipFile.java:252) ~[?:?]
at java.util.zip.ZipFile.<init>(ZipFile.java:181) ~[?:?]
at java.util.jar.JarFile.<init>(JarFile.java:346) ~[?:?]
at java.util.jar.JarFile.<init>(JarFile.java:317) ~[?:?]
at java.util.jar.JarFile.<init>(JarFile.java:283) ~[?:?]
at io.papermc.paper.plugin.provider.source.FileProviderSource.getPluginName(FileProviderSource.java:101) ~[paper-1.20.4.jar:git-Paper-397]
at io.papermc.paper.plugin.provider.source.FileProviderSource.checkUpdate(FileProviderSource.java:76) ~[paper-1.20.4.jar:git-Paper-397]
at io.papermc.paper.plugin.provider.source.FileProviderSource.registerProviders(FileProviderSource.java:49) ~[paper-1.20.4.jar:git-Paper-397]
... 20 more

**Comment by fayer3** [comment]
did you unzip it?

**Comment by Techjar** [comment]
Can you upload the plugin jar you have so we can see what's in it?

**Comment by unknowghost0** [comment]
> did you unzip it?

yes
how else would i be getting the error message

**Comment by unknowghost0** [comment]
you can download it here and see for your self what it has in the .jar
https://github.com/jrbudda/Vivecraft_Spigot_Extensions/releases/download/120r1/Vivecraft_Spigot_Extensions.1.20.4r1.zip

**Comment by fayer3** [comment]
> you can download it here and see for your self what it has in the .jar https://github.com/jrbudda/Vivecraft_Spigot_Extensions/releases/download/120r1/Vivecraft_Spigot_Extensions.1.20.4r1.zip

works fine for me, please upload the jar you have

**Comment by unknowghost0** [comment]
> > you can download it here and see for your self what it has in the .jar https://github.com/jrbudda/Vivecraft_Spigot_Extensions/releases/download/120r1/Vivecraft_Spigot_Extensions.1.20.4r1.zip
> 
> works fine for me, please upload the jar you have

you can't upload .jar files on chat 
We don’t support that file type.

Try again with GIF, JPEG, JPG, MOV, MP4, PNG, SVG, WEBM, CPUPROFILE, CSV, DMP, DOCX, FODG, FODP, FODS, FODT, GZ, JSON, JSONC, LOG, MD, ODF, ODG, ODP, ODS, ODT, PATCH, PDF, PPTX, TGZ, TXT, XLS, XLSX or ZIP.

**Comment by fayer3** [comment]
rename it to .zip then

**Comment by unknowghost0** [comment]
[Vivecraft_Spigot_Extensions.zip](https://github.com/jrbudda/Vivecraft_Spigot_Extensions/files/14039259/Vivecraft_Spigot_Extensions.zip)

**Comment by Techjar** [comment]
Looks like a valid zip file. Maybe you have an anti-malware software that's somehow preventing Paper from reading the plugin?

**Comment by unknowghost0** [comment]
> Looks like a valid zip file. Maybe you have an anti-malware software that's somehow preventing Paper from reading the plugin?

im just wait for owner of plugin to message

**Comment by Techjar** [comment]
What do you mean? We *are* the developers.

**Comment by unknowghost0** [comment]
> What do you mean? We _are_ the developers.

well look like i can't use it because im paying for a server hosting on bisecthosting and ik they don't have a anti-malware

**Comment by Techjar** [comment]
Ah I see. The file must be getting corrupted somehow when you're uploading it to the host. Maybe try using a different method to upload it?

**Comment by unknowghost0** [comment]
I try ftp and website not much way to upload it

**Comment by Techjar** [comment]
Weird. What does the file size say on the server side once you upload it via ftp?

**Comment by unknowghost0** [comment]
> Weird. What does the file size say on the server side once you upload it via ftp?

119kb

**Comment by unknowghost0** [comment]
im asking support real fast on website to find out if there no way to use it ill just drop it and move on

**Comment by Techjar** [comment]
Yeah that file size looks right. Not sure what's going on, definitely seems like an issue with the host at this point.
