### ISSUE TITLE
Possible deprecated method call to bukkit/paper/spigot API

### ISSUE THREAD

**Issue by zaquestion** [jrbudda/Vivecraft_Spigot_Extensions#39]
Got this from paper/spigot
> Please ask the author to give their recipe a static key using NamespacedKey

Not too sure what this means or what additional info is useful. Let me know if I can provide more info.
Error
```
tiles-main_1  | [05:25:46 WARN]: java.lang.Throwable: Warning: A plugin is creating a recipe using a Deprecated method. This will cause you to receive warnings stating 'Tried to load unrecognized recipe: bukkit:<ID>'. Please ask the author to give their recipe a static key using NamespacedKey.
tiles-main_1  | [05:25:46 WARN]:        at org.bukkit.inventory.ShapedRecipe.<init>(ShapedRecipe.java:26)
tiles-main_1  | [05:25:46 WARN]:        at org.vivecraft.VSE.onEnable(VSE.java:93)
tiles-main_1  | [05:25:46 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
tiles-main_1  | [05:25:46 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
tiles-main_1  | [05:25:46 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
tiles-main_1  | [05:25:46 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:387)
tiles-main_1  | [05:25:46 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:336)
tiles-main_1  | [05:25:46 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442)
tiles-main_1  | [05:25:46 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403)
tiles-main_1  | [05:25:46 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341)
tiles-main_1  | [05:25:46 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:292)
tiles-main_1  | [05:25:46 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616)
tiles-main_1  | [05:25:46 WARN]:        at java.lang.Thread.run(Thread.java:748)
```
Server Versions:
```
[05:25:38 INFO]: This server is running Paper version git-Paper-1358 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
[05:25:40 INFO]: [Vivecraft] Loading Vivecraft-Spigot-Extensions v1.12.X-r6
[05:25:40 INFO]: [ProtocolLib] Loading ProtocolLib v4.4.0-SNAPSHOT-b390
```

**Comment by jrbudda** [comment]
OK, just looks like spigot changed something, I'll fix it.

**Comment by jrbudda** [comment]
fixed
