### ISSUE TITLE
NoSuchMethodException on 1.14.4 servers

### ISSUE THREAD

**Issue by QuantumToasted** [jrbudda/Vivecraft_Spigot_Extensions#55]
Hello - I have updated my server to version 1.14.4 (PaperMC build 135) and it seems to be causing warnings to appear in the server console - I'm not sure if the plugin is still functioning correctly as I am not the one taking advantage of it. It seems to be related to Endermen: Here's the stack trace from the console:
```
java.lang.NoSuchMethodException: net.minecraft.server.v1_14_R1.EntityEnderman.dW()
    at java.lang.Class.getDeclaredMethod(Unknown Source)
    at org.vivecraft.VSE.getPrivateMethod(VSE.java:211)
    at org.vivecraft.entities.CustomPathFinderGoalPlayerWhoLookedAtTarget.<init>(CustomPathFinderGoalPlayerWhoLookedAtTarget.java:31)
    at org.vivecraft.VSE.EditEntity(VSE.java:275)
    at org.vivecraft.VSE.onEvent(VSE.java:239)
    at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor105.execute(Unknown Source)
    at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545)
    at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callCreatureSpawnEvent(CraftEventFactory.java:613)
    at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:534)
    at net.minecraft.server.v1_14_R1.WorldServer.addEntity0(WorldServer.java:967)
    at net.minecraft.server.v1_14_R1.WorldServer.addEntity(WorldServer.java:889)
    at net.minecraft.server.v1_14_R1.SpawnerCreature.spawnMobs(SpawnerCreature.java:124)
    at net.minecraft.server.v1_14_R1.ChunkProviderServer.lambda$tickChunks$7(ChunkProviderServer.java:496)
    at it.unimi.dsi.fastutil.longs.Long2ObjectLinkedOpenHashMap$1.forEach(Long2ObjectLinkedOpenHashMap.java:1661)
    at com.google.common.collect.Iterables$UnmodifiableIterable.forEach(Iterables.java:105)
    at net.minecraft.server.v1_14_R1.ChunkProviderServer.tickChunks(ChunkProviderServer.java:445)
    at net.minecraft.server.v1_14_R1.ChunkProviderServer.tick(ChunkProviderServer.java:415)
    at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:266)
    at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1204)
    at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:420)
    at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1076)
    at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:920)
    at java.lang.Thread.run(Unknown Source)
```

**Comment by jrbudda** [comment]
ah, so much for the whole 1.14.x thing. Will have to rebuild for 1.14.4

**Comment by ReadyPlayerEmma** [comment]
I am also seeing this error, and am also on 1.14.4 (PaperMC build 135).

@jrbudda , does your message above mean that it's just a matter of rebuilding to get everything working? If so, are you about to publish a rebuild because of that? If not, should I be able to just re-build my own without any code changes and resolve the error?

Also, thanks for all the awesome work you do!

**Comment by jrbudda** [comment]
It looks like some minor code changes are needed. There is no Vivecraft for .4 yet so just remove VSE for now.

**Comment by jrbudda** [comment]
plugin is updated

**Comment by QuantumToasted** [comment]
Does this plugin need to be built from source for 1.14.4 compat or will there be something on the Releases page soon?
