### ISSUE TITLE
Yatopia Monster Spawn Conflict

### ISSUE THREAD

**Issue by LittleBigBug** [jrbudda/Vivecraft_Spigot_Extensions#72]
Hello!

As you can tell, I am running a server using "[Yatopia](https://github.com/YatopiaMC/Yatopia)" which is a fork of paper that includes many optimization patches, of their own, and many taken from other repos like Purpur and EMC. I'm sure this may cause issues with some plugins but so far I have had none, however I think this issue has yatopia to blame, they use a custom optimized linked hash set object.

```
[02:44:35 ERROR]: Could not pass event CreatureSpawnEvent to Vivecraft-Spigot-Extensions v1.16.3-r1
java.lang.ClassCastException: it.unimi.dsi.fastutil.objects.ObjectLinkedOpenHashSet cannot be cast to java.util.LinkedHashSet
at org.vivecraft.VSE.EditEntity(VSE.java:322) ~[?:?]
at org.vivecraft.VSE.onEvent(VSE.java:305) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor230.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.3.jar:git-Yatopia-"0faeed7"]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.3.jar:git-Yatopia-"0faeed7"]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.3.jar:git-Yatopia-"0faeed7"]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.3.jar:git-Yatopia-"0faeed7"]
at org.bukkit.craftbukkit.v1_16_R2.event.CraftEventFactory.callCreatureSpawnEvent(CraftEventFactory.java:673) ~[patched_1.16.3.jar:git-Yatopia-"0faeed7"]
at org.bukkit.craftbukkit.v1_16_R2.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:594) ~[patched_1.16.3.jar:git-Yatopia-"0faeed7"]
at net.minecraft.server.v1_16_R2.WorldServer.addEntity0(WorldServer.java:1678) ~[patched_1.16.3.jar:git-Yatopia-"0faeed7"]
at net.minecraft.server.v1_16_R2.WorldServer.addEntity(WorldServer.java:1579) ~[patched_1.16.3.jar:git-Yatopia-"0faeed7"]
at net.minecraft.server.v1_16_R2.WorldAccess.lambda$addAllEntities$0(WorldAccess.java:13) ~[patched_1.16.3.jar:git-Yatopia-"0faeed7"]
at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:419) ~[?:1.8.0_242]
at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:742) ~[?:1.8.0_242]
at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:647) ~[?:1.8.0_242]
at net.minecraft.server.v1_16_R2.WorldAccess.addAllEntities(WorldAccess.java:13) ~[patched_1.16.3.jar:git-Yatopia-"0faeed7"]
at net.minecraft.server.v1_16_R2.SpawnerCreature.spawnMobsInternal(SpawnerCreature.java:261) ~[patched_1.16.3.jar:git-Yatopia-"0faeed7"]
at net.minecraft.server.v1_16_R2.SpawnerCreature.spawnMobs(SpawnerCreature.java:187) ~[patched_1.16.3.jar:git-Yatopia-"0faeed7"]
at net.minecraft.server.v1_16_R2.SpawnerCreature.a(SpawnerCreature.java:158) ~[patched_1.16.3.jar:git-Yatopia-"0faeed7"]
at net.minecraft.server.v1_16_R2.ChunkProviderServer.tickChunks(ChunkProviderServer.java:1030) ~[patched_1.16.3.jar:git-Yatopia-"0faeed7"]
at net.minecraft.server.v1_16_R2.ChunkProviderServer.tick(ChunkProviderServer.java:926) ~[patched_1.16.3.jar:git-Yatopia-"0faeed7"]
at net.minecraft.server.v1_16_R2.WorldServer.doTick(WorldServer.java:887) ~[patched_1.16.3.jar:git-Yatopia-"0faeed7"]
at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1434) ~[patched_1.16.3.jar:git-Yatopia-"0faeed7"]
at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:390) ~[patched_1.16.3.jar:git-Yatopia-"0faeed7"]
at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1282) ~[patched_1.16.3.jar:git-Yatopia-"0faeed7"]
at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:1007) ~[patched_1.16.3.jar:git-Yatopia-"0faeed7"]
at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:165) ~[patched_1.16.3.jar:git-Yatopia-"0faeed7"]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]```

**Comment by Techjar** [comment]
Who the fuck's messing with types on internal nms fields?
