### ISSUE TITLE
Plugin crashes onEnable

### ISSUE THREAD

**Issue by infinytum** [jrbudda/Vivecraft_Spigot_Extensions#76]
Basically when you drop the 1.16.3 build of this plugin into the plugins folder, the plugin crashes onEnable with a casting error. 

openjdk version "1.8.0_212"
OpenJDK Runtime Environment (IcedTea 3.12.0) (Alpine 8.212.04-r0)
OpenJDK 64-Bit Server VM (build 25.252-b09, mixed mode)

```
Error occurred while enabling Vivecraft-Spigot-Extensions v1.16.3-r1 (Is it up to date?)
15/11/2020 17:47:43 java.lang.ClassCastException: it.unimi.dsi.fastutil.objects.ObjectLinkedOpenHashSet cannot be cast to java.util.LinkedHashSet
15/11/2020 17:47:43 	at org.vivecraft.VSE.EditEntity(VSE.java:333) ~[?:?]
15/11/2020 17:47:43 	at org.vivecraft.VSE.CheckAllEntities(VSE.java:313) ~[?:?]
15/11/2020 17:47:43 	at org.vivecraft.VSE.onEnable(VSE.java:206) ~[?:?]
15/11/2020 17:47:43 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.3.jar:git-Yatopia-"0dd46b6"]
15/11/2020 17:47:43 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.3.jar:git-Yatopia-"0dd46b6"]
15/11/2020 17:47:43 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.3.jar:git-Yatopia-"0dd46b6"]
15/11/2020 17:47:43 	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.3.jar:git-Yatopia-"0dd46b6"]
15/11/2020 17:47:43 	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.3.jar:git-Yatopia-"0dd46b6"]
15/11/2020 17:47:43 	at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:469) ~[patched_1.16.3.jar:git-Yatopia-"0dd46b6"]
15/11/2020 17:47:43 	at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:257) ~[patched_1.16.3.jar:git-Yatopia-"0dd46b6"]
15/11/2020 17:47:43 	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:943) ~[patched_1.16.3.jar:git-Yatopia-"0dd46b6"]
15/11/2020 17:47:43 	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:178) ~[patched_1.16.3.jar:git-Yatopia-"0dd46b6"]
15/11/2020 17:47:43 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

```

**Comment by Techjar** [comment]
I thought we fixed this shit.

**Comment by Techjar** [comment]
Oh, right. We never did a 1.16.3 r2. For Yatopia compatibility, ou'll have to build 9bb2ca5712791b233a56af17ea8af494af980206 yourself, or use 1.16.4.

**Comment by infinytum** [comment]
I'll try 1.16.4 and let you know how it goes! Thanks for that super-fast response!

**Comment by Techjar** [comment]
Yeah may as well use 1.16.4 at this point, unless there's some plugin you really need that isn't updated yet.

**Comment by infinytum** [comment]
Yup, updating worked! This is resolved for me then :) Thanks for your assistance
