### ISSUE TITLE
Could not pass event PlayerJoinEvent to Vivecraft-Spigot-Extensions v1.16.4-r1

### ISSUE THREAD

**Issue by Stixil** [jrbudda/Vivecraft_Spigot_Extensions#77]
Version: Paper-288 MC 1.16.4

[20:28:05 ERROR]: Could not pass event PlayerJoinEvent to Vivecraft-Spigot-Extensions v1.16.4-r1
java.util.NoSuchElementException: packet_handler
        at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:1119) ~[patched_1.16.4.jar:git-Paper-294]
        at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:260) ~[patched_1.16.4.jar:git-Paper-294]
        at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:249) ~[patched_1.16.4.jar:git-Paper-294]
        at com.comphenix.protocol.injector.netty.PipelineProxy.addBefore(PipelineProxy.java:61) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3$1.addBefore(ChannelInjector.java:287) ~[?:?]
        at org.vivecraft.VSE.onPlayerConnect(VSE.java:439) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor331.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.4.jar:git-Paper-294]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.4.jar:git-Paper-294]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.4.jar:git-Paper-294]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.4.jar:git-Paper-294]
        at net.minecraft.server.v1_16_R3.PlayerList.postChunkLoadJoin(PlayerList.java:273) ~[patched_1.16.4.jar:git-Paper-294]
        at net.minecraft.server.v1_16_R3.PlayerList.lambda$null$1(PlayerList.java:220) ~[patched_1.16.4.jar:git-Paper-294]
        at net.minecraft.server.v1_16_R3.PlayerConnection.tick(PlayerConnection.java:165) ~[patched_1.16.4.jar:git-Paper-294]
        at net.minecraft.server.v1_16_R3.NetworkManager.a(NetworkManager.java:388) ~[patched_1.16.4.jar:git-Paper-294]
        at net.minecraft.server.v1_16_R3.ServerConnection.c(ServerConnection.java:145) ~[patched_1.16.4.jar:git-Paper-294]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1384) ~[patched_1.16.4.jar:git-Paper-294]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.4.jar:git-Paper-294]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1212) ~[patched_1.16.4.jar:git-Paper-294]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1000) ~[patched_1.16.4.jar:git-Paper-294]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.4.jar:git-Paper-294]
        at java.lang.Thread.run(Unknown Source) [?:?]

**Comment by TheCreeperCow** [comment]
According to the code this causes problems in the aimfix for ViveCraft not sure why packet_handler is no longer a method unless paper decided to deviate from spigot again could you please test this on normal spigot and tell me if it happens again
