### ISSUE TITLE
Any timeline on 1.18.2 release?

### ISSUE THREAD

**Issue by pomtom44** [jrbudda/Vivecraft_Spigot_Extensions#88]
Just updated my server and getting error enabling 1.18.1-b2

Assuming its 1.18.1 vs 1.18.2 related?

Error log below if needed

[14:24:54 ERROR]: Error occurred while enabling Vivecraft-Spigot-Extensions v1.18.1-b2 (Is it up to date?)
java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_18_R1/inventory/CraftItemStack
        at org.vivecraft.VSE.setLocalizedItemName(VSE.java:201) ~[Vivecraft_Spigot_Extensions_1.18.1b2.jar:?]
        at org.vivecraft.VSE.onEnable(VSE.java:93) ~[Vivecraft_Spigot_Extensions_1.18.1b2.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:559) ~[paper-1.18.2.jar:git-Paper-252]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:473) ~[paper-1.18.2.jar:git-Paper-252]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:664) ~[paper-1.18.2.jar:git-Paper-252]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431) ~[paper-1.18.2.jar:git-Paper-252]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:316) ~[paper-1.18.2.jar:git-Paper-252]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1163) ~[paper-1.18.2.jar:git-Paper-252]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-252]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_18_R1.inventory.CraftItemStack
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        ... 13 more
[14:24:54 INFO]: [Vivecraft] Disabling Vivecraft-Spigot-Extensions v1.18.1-b2

**Comment by Espergium** [comment]
This is mentioned in the news channel of the discord, and by the bot should you mention the version number.

**Comment by pomtom44** [comment]
ah, didnt think to check discord, i dont use it much, 
ok will check there for updates
