### ISSUE TITLE
not starting with server, spigot

### ISSUE THREAD

**Issue by aldumgames** [jrbudda/Vivecraft_Spigot_Extensions#89]
[23:56:28] [Server thread/ERROR]: Error occurred while enabling Vivecraft-Spigot-Extensions v1.18.2-1 (Is it up to date?)
java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_18_R2/inventory/CraftItemStack
	at org.vivecraft.VSE.setLocalizedItemName(VSE.java:201) ~[Vivecraft_Spigot_Extensions.jar:?]
	at org.vivecraft.VSE.onEnable(VSE.java:93) ~[Vivecraft_Spigot_Extensions.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:563) ~[paper-1.18.1.jar:git-Paper-68]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:477) ~[paper-1.18.1.jar:git-Paper-68]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:727) ~[paper-1.18.1.jar:git-Paper-68]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:503) ~[paper-1.18.1.jar:git-Paper-68]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:313) ~[paper-1.18.1.jar:git-Paper-68]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1202) ~[paper-1.18.1.jar:git-Paper-68]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-68]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_18_R2.inventory.CraftItemStack
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	... 13 more

**Comment by fayer3** [comment]
get the 1.18.1 version from here https://www.spigotmc.org/resources/vivecraft-spigot-extensions.33166/history

**Comment by aldumgames** [comment]
> get the 1.18.1 version from here https://www.spigotmc.org/resources/vivecraft-spigot-extensions.33166/history

thank will try one sec

**Comment by aldumgames** [comment]
that worked thanks
